#!/usr/bin/env bash
# run_vllm_with_bkvt.sh — launch a vLLM server with BeyondKVTransfer tracing.
#
# Usage:
#   ./scripts/run_vllm_with_bkvt.sh [vllm serve arguments...]
#
# Environment variables you can override before running:
#   BKVT_OUTPUT_DIR   (default: ./bkvt_traces)
#   BKVT_PROFILE      (default: full)
#   BKVT_TRACE_ID     (default: auto-generated UUID)
#   MODEL             (default: meta-llama/Meta-Llama-3-8B-Instruct)
#
# Examples:
#   # Basic run with Llama-3-8B
#   MODEL=meta-llama/Meta-Llama-3-8B-Instruct ./scripts/run_vllm_with_bkvt.sh
#
#   # Coarse profile (lower overhead) with custom output dir
#   BKVT_PROFILE=coarse BKVT_OUTPUT_DIR=/mnt/traces \
#       ./scripts/run_vllm_with_bkvt.sh --tensor-parallel-size 2
#
#   # Request-only profile (minimal overhead, good for baselines)
#   BKVT_PROFILE=request_only ./scripts/run_vllm_with_bkvt.sh
#
# Notes:
#   * Requires BKVT to be installed: pip install -e /path/to/BeyondKVTransfer
#   * Requires vLLM v1 to be installed alongside BKVT.
#   * The script patches vLLM at import time via PYTHONSTARTUP so no vLLM
#     source modification is needed.
# ---------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

# ── Default settings ────────────────────────────────────────────────────────
export BKVT_ENABLE="${BKVT_ENABLE:-1}"
export BKVT_OUTPUT_DIR="${BKVT_OUTPUT_DIR:-./bkvt_traces}"
export BKVT_PROFILE="${BKVT_PROFILE:-full}"
export BKVT_SAMPLE_TOKEN="${BKVT_SAMPLE_TOKEN:-0.05}"
export BKVT_SAMPLE_METADATA="${BKVT_SAMPLE_METADATA:-1.0}"
export BKVT_SAMPLE_TRANSFER="${BKVT_SAMPLE_TRANSFER:-1.0}"
export BKVT_SYS_COUNTER_HZ="${BKVT_SYS_COUNTER_HZ:-10}"

MODEL="${MODEL:-meta-llama/Meta-Llama-3-8B-Instruct}"

# ── Print banner ────────────────────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════════╗"
echo "║          BeyondKVTransfer — vLLM trace run           ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  BKVT_ENABLE        = ${BKVT_ENABLE}                 ║"
echo "║  BKVT_OUTPUT_DIR    = ${BKVT_OUTPUT_DIR}             ║"
echo "║  BKVT_PROFILE       = ${BKVT_PROFILE}                ║"
echo "║  BKVT_SAMPLE_TOKEN  = ${BKVT_SAMPLE_TOKEN}           ║"
echo "║  MODEL              = ${MODEL}                       ║"
echo "╚══════════════════════════════════════════════════════╝"

mkdir -p "${BKVT_OUTPUT_DIR}"

# ── Build the Python patch-apply snippet ────────────────────────────────────
# We use PYTHONSTARTUP so the patch runs before vLLM engine init.
# (For production use you may prefer a sitecustomize.py or conftest.)
PATCH_SCRIPT="$(mktemp /tmp/bkvt_patch_XXXXXX.py)"
trap 'rm -f "$PATCH_SCRIPT"' EXIT

cat > "$PATCH_SCRIPT" <<'PYEOF'
# Auto-generated by run_vllm_with_bkvt.sh — do not edit.
import os, logging
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(name)s %(levelname)s %(message)s")
if os.environ.get("BKVT_ENABLE", "0") == "1":
    try:
        from bkvt.integrations.vllm.patch import apply as _bkvt_apply
        result = _bkvt_apply()
        import logging as _lg
        _lg.getLogger("bkvt").info("bkvt patch result: %s", result)
    except Exception as _e:
        import logging as _lg
        _lg.getLogger("bkvt").warning("bkvt patch failed: %s", _e)
PYEOF

export PYTHONSTARTUP="$PATCH_SCRIPT"

# ── Launch vLLM ─────────────────────────────────────────────────────────────
echo ""
echo "Launching: python -m vllm.entrypoints.openai.api_server --model ${MODEL} $*"
echo ""

exec python -m vllm.entrypoints.openai.api_server \
    --model "${MODEL}" \
    "$@"
